[package]
name = "xrandr-tool"
version = "0.1.0"
authors = ["Tethys Svensson <freaken@freaken.dk>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
paw = "1.0.0"
structopt = { version = "0.3.21", features = [ "paw" ] }
